mining:
  # Миры, в которых работает система
  worlds:
    - 'world'
  startSpeed: 25.0 # В процентах
  critTempBonus: 25.0 # Бонус к скорости добычи для текущего блока при условии выполненого крита
  critStreakBonus: 0.01 # Бонус к скорости добычи за каждый крит
messages:
  critMessage: '&7Crit Streak: &a${count}&7 (&e+${speed}&7 Скорость добычи)'
  critFailMessage: '&7Crit Streak: &c${count}&7 (&e+${speed}&7 Скорость добычи)'
  uselessTool: '&cЭто не самый подходящий инструмент'

# Дропать ли предмет из блока, или сразу выдавать игроку
dropItem: false

# Настройка дропа для каждого блока.
# Если какого-то блока здесь нет - дроп с него будет дефолтный
drop:
  COAL_ORE:
    drop: COAL # ID предмета
    amount: 1 # Кол-во предметов
    replaceBlock: STONE # Блок, на который заменится ископаемый. Эта строчка может отсутствовать, в таком случае блок просто удалится
  EMERALD_ORE:
    drop: EMERALD
    amount: 1
    replaceBlock: STONE

# Черный список блоков. Блоки находящиеся в этом списке не будут добываться, и им не наносится урон игроком
blockBlackList:
  - STONE
  - GRASS